### ISSUE TITLE
CX Incorrect_Permission_Assignment_For_Critical_Resources @ src/main/java/org/cysecurity/cspf/jvl/controller/Logout.java [main]

### ISSUE THREAD

**Issue by nidhi0512** [satyamchaurasiapersistent/CxFlowBodgeit#111]
**Incorrect_Permission_Assignment_For_Critical_Resources** issue exists @ **src/main/java/org/cysecurity/cspf/jvl/controller/Logout.java** in branch **main**

*A file is created on the file system by out&nbsp;in&nbsp;src\main\java\org\cysecurity\cspf\jvl\controller\Logout.java at line&nbsp;36 with potentially dangerous permissions.
Similarity ID: 417749957*

Severity: Low

CWE:732

[Checkmarx](https://sast94.cxquality.com/CxWebClient/ViewerMain.aspx?scanid=1005678&projectid=453&pathid=1532)

[Training](null)
[Recommended Fix](https://sast94.cxquality.com/CxWebClient/ScanQueryDescription.aspx?queryID=3884&queryVersionCode=96427443&queryTitle=Incorrect_Permission_Assignment_For_Critical_Resources)

Lines: [36](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Logout.java#L36) 

---
[Code (Line #36):](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Logout.java#L36)
```
PrintWriter out = response.getWriter();
```
---

**Comment by satyamchaurasiapersistent** [comment]
Issue still exists.
