### ISSUE TITLE
CX Incorrect_Permission_Assignment_For_Critical_Resources @ src/main/java/org/cysecurity/cspf/jvl/controller/Install.java [main]

### ISSUE THREAD

**Issue by nidhi0512** [satyamchaurasiapersistent/CxFlowBodgeit#112]
**Incorrect_Permission_Assignment_For_Critical_Resources** issue exists @ **src/main/java/org/cysecurity/cspf/jvl/controller/Install.java** in branch **main**

*A file is created on the file system by fileout&nbsp;in&nbsp;src\main\java\org\cysecurity\cspf\jvl\controller\Install.java at line&nbsp;72 with potentially dangerous permissions.
Similarity ID: -132850943

A file is created on the file system by out&nbsp;in&nbsp;src\main\java\org\cysecurity\cspf\jvl\controller\Install.java at line&nbsp;79 with potentially dangerous permissions.
Similarity ID:...*

Severity: Low

CWE:732

[Checkmarx](https://sast94.cxquality.com/CxWebClient/ViewerMain.aspx?scanid=1005678&projectid=453&pathid=1515)

[Training](null)
[Recommended Fix](https://sast94.cxquality.com/CxWebClient/ScanQueryDescription.aspx?queryID=3884&queryVersionCode=96427443&queryTitle=Incorrect_Permission_Assignment_For_Critical_Resources)

Lines: [72](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Install.java#L72) [79](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Install.java#L79) 

---
[Code (Line #72):](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Install.java#L72)
```
FileOutputStream fileout = new FileOutputStream(configPath);
```
---
[Code (Line #79):](https://gitlab.com/c8698/CxFlowBodgeit/blob/main/src/main/java/org/cysecurity/cspf/jvl/controller/Install.java#L79)
```
PrintWriter out = response.getWriter();
```
---

**Comment by satyamchaurasiapersistent** [comment]
Issue still exists.
