### ISSUE TITLE
CX Cross_Site_History_Manipulation @ src/main/java/org/cysecurity/cspf/jvl/controller/LoginValidator.java [master]

### ISSUE THREAD

**Issue by nidhi0512** [satyamchaurasiapersistent/CxFlowBodgeit#120]
**Cross_Site_History_Manipulation** issue exists @ **src/main/java/org/cysecurity/cspf/jvl/controller/LoginValidator.java** in branch **master**

*Method processRequest at line 53 of src\main\java\org\cysecurity\cspf\jvl\controller\LoginValidator.java may leak server-side conditional values, enabling user tracking from another website. This may constitute a Privacy Violation.
*

Severity: Low

CWE:203

[Checkmarx](http://SAST-PI-30/CxWebClient/ViewerMain.aspx?scanid=1001110&projectid=262&pathid=437)

[Training](null)
[Recommended Fix](http://SAST-PI-30/CxWebClient/ScanQueryDescription.aspx?queryID=627&queryVersionCode=56492507&queryTitle=Cross_Site_History_Manipulation)

Lines: [53](https://gitlab.com/c8698/CxFlowBodgeit/blob/master/src/main/java/org/cysecurity/cspf/jvl/controller/LoginValidator.java#L53) 

---
[Code (Line #53):](https://gitlab.com/c8698/CxFlowBodgeit/blob/master/src/main/java/org/cysecurity/cspf/jvl/controller/LoginValidator.java#L53)
```
if(rs != null && rs.next()){
```
---

**Comment by nidhi0512** [comment]
Issue still exists.

**Comment by satyamchaurasiapersistent** [comment]
Issue still exists.
