### ISSUE TITLE
CX Improper_Resource_Access_Authorization @ src/main/webapp/ForgotPassword.jsp [master]

### ISSUE THREAD

**Issue by nidhi0512** [satyamchaurasiapersistent/CxFlowBodgeit#121]
**Improper_Resource_Access_Authorization** issue exists @ **src/main/webapp/ForgotPassword.jsp** in branch **master**

*An I\O action occurs at&nbsp;src\main\webapp\ForgotPassword.jsp&nbsp;in&nbsp;42 without authorization checks.
*

Severity: Low

CWE:285

[Checkmarx](http://SAST-PI-30/CxWebClient/ViewerMain.aspx?scanid=1001110&projectid=262&pathid=622)

[Training](null)
[Recommended Fix](http://SAST-PI-30/CxWebClient/ScanQueryDescription.aspx?queryID=3890&queryVersionCode=96496887&queryTitle=Improper_Resource_Access_Authorization)

Lines: [42](https://gitlab.com/c8698/CxFlowBodgeit/blob/master/src/main/webapp/ForgotPassword.jsp#L42) 

---
[Code (Line #42):](https://gitlab.com/c8698/CxFlowBodgeit/blob/master/src/main/webapp/ForgotPassword.jsp#L42)
```
rs=stmt.executeQuery("select * from users where username='"+request.getParameter("username").trim()+"' and secret='"+request.getParameter("secret")+"'");
```
---

**Comment by nidhi0512** [comment]
Issue still exists.

**Comment by satyamchaurasiapersistent** [comment]
Issue still exists.
